---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nvidia-gpu-operator
commonLabels:
  component: nvidia-gpu-operator
resources:
- namespace.yaml
- operatorgroup.yaml
- gpu-operator-certified.yaml
- clusterpolicy.yaml
