---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-nfd
commonLabels:
  component: openshift-nfd
resources:
- namespace.yaml
- operatorgroup.yaml
- nfd.yaml
- nfd-instance.yaml
