---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redhat-ods-applications
commonLabels:
  component: redhat-ods-applications
resources:
  - namespace.yaml
  - imagestream.yaml
  - acceleratorprofile.yaml
