---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redhat-ods-operator
commonLabels:
  component: redhat-ods-operator
resources:
  - namespace.yaml
  - imagestream.yaml
  - acceleratorprofile.yaml
