---
apiVersion: v1
kind: Namespace
metadata:
  name: llm-serving
  labels:
    app: llm-serving
    kubernetes.io/metadata.name: llm-serving
    modelmesh-enabled: "false"
    opendatahub.io/dashboard: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    openshift.io/description: "llm-serving"
    openshift.io/display-name: llm-serving
