apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: nvidia-gpu
  namespace: redhat-ods-applications
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  description: ""
  displayName: NVIDIA GPU
  enabled: true
  identifier: nvidia.com/gpu
  tolerations: []
